version: '3'
services:
    mysql:
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: main
            MYSQL_USER: user
            MYSQL_PASSWORD: password
            MYSQL_TCP_PORT: ${MYSQL_PORT}
        ports:
          - "${MYSQL_PORT}:${MYSQL_PORT}"
